version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: spend-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db
      - ./backend/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  backend:
    build: ./backend
    container_name: spend-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/spend_db?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-2024
      PORT: 8080
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app

  ai-service:
    build: ./ai-service
    container_name: spend-ai-service
    restart: always
    ports:
      - "8000:8000"
    environment:
      OLLAMA_URL: http://host.docker.internal:11434
      AI_MODEL: deepseek-r1:8b
      BACKEND_URL: http://backend:8080
    depends_on:
      - backend
    volumes:
      - ./ai-service:/app

  frontend:
    build: ./frontend
    container_name: spend-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8080
      REACT_APP_AI_SERVICE_URL: http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongodb_data:
